"""Stub for comfy.ldm.hunyuan_video.upsampler.

Provides HunyuanVideo15SRModel for compatibility.
"""


class HunyuanVideo15SRModel:
    """Stub for Hunyuan Video 1.5 super-resolution model.

    Upscales video frames generated by the Hunyuan Video pipeline.
    """

    def __init__(self, **kwargs):
        """Initialize HunyuanVideo15SRModel.

        Args:
            **kwargs: Model configuration.
        """
        pass
